### ISSUE TITLE
Roo does not wait for `npm run build` mode which in a nextjs application could take a few ms in next js apps

### ISSUE THREAD

**Issue by ramakay** [RooVetGit/Roo-Code#2113]
### App Version

3.10.5

### API Provider

Glama

### Model Used

Claude 3.7 sonnet

### Actual vs. Expected Behavior

When asking Roo to run a `npm run build&&npm run start` command to ensure it tests the server output on a production build, it routinely kills the server despite different asks to create a new terminal window or sleep - see steps below. 

How can i ensure a production build is created and tested. 

### Detailed Steps to Reproduce

1. create any nextjs app
2. create a task that instructs to run npm run build and ensure it runs properly (see below)

sample task that does not wait for `npm run build ` to complete 
```
<verification_checklist>
build_verification:
  name: verify_build_before_completion
  description: Requires successful build verification before marking any task as complete
  filters:
    - type: content
      pattern: "(?i)\\b(task complete|completed|finished|done|ready for review)\\b"
    - type: intent
      pattern: "skip_verification"
    - type: content
      pattern: "npm run build"
  actions:
    - type: reject
      message: |
        Build verification is mandatory before completing this task:
        
        You MUST run the following verification sequence:
        1. Run `npm run build && npm run start` and wait until you see "ready - started server on 0.0.0.0:3000"
        2. Confirm application loads in browser (screenshot required)
        3. Verify all acceptance criteria still pass
        
        This verification sequence cannot be skipped or partially completed.
    - type: require
      condition: "before_completion"
      steps:
        - command: "npm run build && npm run start"
          wait_for: "ready - started server on 0.0.0.0:3000"
          verify: "browser_screenshot"
        - verify: "acceptance_criteria"

checks:
  - Verify API client correctly handles different HTTP methods
  - Test API client with mock responses to ensure proper parsing
  - Confirm error handling works for different error scenarios
  - Test API endpoints with sample data
  - Verify React hooks correctly manage loading and error states
  - Test API functions with network errors to ensure proper handling
  - Confirm API client uses the correct base URL from configuration
  - Verify TypeScript types are correctly defined for all API functions
  - Test integration with the backend API if available
</verification_checklist>
``` 

Sample run - note i attempted to add a 15s delay 

```
> next build

   ▲ Next.js 15.2.4
   - Environments: .env.local, .env.production

   Creating an optimized production build ...
sleep 15 && echo "Waited 15 seconds for build to complete and server to start"              
``` 

### Relevant API Request Output

```shell

```
